services:
  ordersystem.apigateway:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:8080"
    ports: 
      - "30000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  orderservice:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:8080"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  orderservicedapr:
    command: ["./daprd", "-app-id", "orderservice", "-app-port", "8080"] #, "-dapr-http-port", "32000", "-dapr-grpc-port", "3800"] #, "-resources-path", "/components"]
    volumes:
      - ./components:/components
    network_mode: "service:orderservice"

  ordersystem.paymentservice.api:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:8080"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ordersystem.warehouseservice.api:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:8080"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
